version: 2
updates:
- package-ecosystem: "npm"
  directory: "/frontend"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 3
  reviewers:
  - deissh
  assignees:
  - deissh
  labels:
  - dependencies
  - area/frontend
- package-ecosystem: gomod
  directory: "/ayako"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  reviewers:
  - deissh
  assignees:
  - deissh
  labels:
  - dependencies
  - area/ayako
